### ISSUE TITLE
Switch to Nightwatch ?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-nightwatch#2]
http://nightwatchjs.org/
http://nightwatchjs.org/guide#installation
thanks to @gabrielperales for reminding us about this... :+1:

**Comment by gabrielperales** [comment]
and what about [http://zombie.js.org/](https://github.com/assaf/zombie) ?

**Comment by gabrielperales** [comment]
oh!, I have found an *awesome like* list with headless Browsers https://github.com/dhamaniasad/HeadlessBrowsers there are so many!

**Comment by nelsonic** [comment]
@gabrielperales interesting how that list does not *mention* nightwatch... indeed there are many.
